services:
  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: techstore-postgres-dev
    environment:
      POSTGRES_DB: techstore_dev
      POSTGRES_USER: techstore_user
      POSTGRES_PASSWORD: techstore_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - techstore-dev-network

  # H2 Database Console (Alternative for development)
  h2-console:
    image: oscarfonts/h2:latest
    container_name: techstore-h2-console
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - h2_data:/opt/h2-data
    networks:
      - techstore-dev-network

  # Application in Development Mode
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: techstore-api-dev
    environment:
      SPRING_PROFILES_ACTIVE: development
      DATABASE_URL: jdbc:postgresql://postgres-dev:5432/techstore_dev
      DATABASE_USERNAME: techstore_user
      DATABASE_PASSWORD: techstore_password
    ports:
      - "8081:8080"
      - "5005:5005"  # Debug port
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    depends_on:
      - postgres-dev
    networks:
      - techstore-dev-network
    command: >
      sh -c "mvn spring-boot:run -Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"

volumes:
  postgres_dev_data:
  h2_data:
  maven_cache:

networks:
  techstore-dev-network:
    driver: bridge