
spring:
    application:
        name: tech-store-api

    # Database Configuration
    datasource:
        url: jdbc:postgresql://postgres:5432/techstore
        username: techstore_user
        password: techstore_password
        driver-class-name: org.postgresql.Driver

    # JPA/Hibernate Configuration
    jpa:
        hibernate:
            ddl-auto: update # Use 'update' in production / 'create-drop in dev'
        show-sql: false
        properties:
            hibernate:
                jdbc:
                    batch_size: 30
                order_inserts: true
                order_updates: true
                format_sql: true
                use_sql_comments: true
                default_batch_fetch_size: 20
                search:
                    backend:
                        type: lucene
                        directory:
                            root: /tmp/lucene/indexes


    # Connection Pool Configuration
    hikari:
        maximum-pool-size: 3  # Увеличи значително
        minimum-idle: 10
        connection-timeout: 10000
        idle-timeout: 300000
        max-lifetime: 1800000
        leak-detection-threshold: 5000

    # Jackson Configuration
    jackson:
        serialization:
            fail-on-empty-beans: false
            write-dates-as-timestamps: false
        deserialization:
            fail-on-unknown-properties: false
        time-zone: UTC

    # Multipart Configuration (for file uploads)
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB

    # Profile Configuration
    profiles:
        active: production

aws:
    s3:
        access-key: ${AWS_ACCESS_KEY:aws-s3-key}
        secret-key: ${AWS_SECRET_KEY:aws-s3-secret-key}
        bucket-name: ${AWS_S3_BUCKET_NAME:aws-s3-name}
        region: ${AWS_S3_REGION:us-east-1}

# Server Configuration
server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param  # Include stack trace only when trace=true parameter is passed
        include-exception: false
    servlet:
        encoding:
            charset: UTF-8
            enabled: true

# LOGGING CONFIGURATION
logging:
    level:
        org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl: WARN
        org.hibernate.SQL: WARN
        org.hibernate.type.descriptor.sql: WARN
        org.hibernate.tool.schema: WARN
        com.zaxxer.hikari: WARN
        org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
        org.springframework.security.web.FilterChainProxy: WARN
        org.hibernate.type.descriptor.sql.BasicBinder: ERROR
        com.techstore: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
        name: logs/techstore.log
    logback:
        rollingpolicy:
            max-file-size: 10MB
            max-history: 30
            total-size-cap: 300MB

# Application Specific Configuration
app:
    # Error handling configuration
    error:
        include-stack-trace: false  # Set to true in development
        include-root-cause: true
        max-error-details: 10
    sync:
        enabled: true
        cron: "0 0 2 * * *"  # 2:00 AM всеки ден
        batch-size: 30       # Chunks от 30 записа
        max-chunk-duration-minutes: 5

    markup:
        default-percentage: 20.0
        max-percentage: 200.0
        min-percentage: -50.0

    # JWT Configuration
    jwt:
        secret: ${JWT_SECRET:techStoreSecretKeyThatShouldBeLongAndSecure123456789}
        expiration: 86400000 # 24 hours in milliseconds
        refresh-expiration: 604800000 # 7 days in milliseconds

    # File Upload Configuration
    upload:
        directory: ${UPLOAD_DIR:./uploads}
        max-file-size: 10485760 # 10MB
        allowed-extensions: jpg,jpeg,png,gif,webp

    # Admin Configuration
    admin:
        default-username: admin
        default-password: ${ADMIN_PASSWORD:admin123}
        default-email: admin@techstore.com

    # Pagination Configuration
    pagination:
        default-size: 20
        max-size: 100

# Management/Actuator Configuration
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    endpoint:
        health:
            show-details: when-authorized

# OpenAPI/Swagger Configuration
springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html

vali:
    api:
        base-url: https://www.vali.bg/api/v1
        token: v8GPrGyODgy6Em8VwcYTXB6WJvjYG7qAgYVSmNyMQGWdgT4lVCGAh1a1tR5K
        timeout: 30000
        retry-attempts: 3
        retry-delay: 1000


